amilio_user:
    resource: "@AmilioUserBundle/Resources/config/routing.yml"
    prefix:   /

amilio_shop:
    resource: "@AmilioRetrieverBundle/Resources/config/routing.yml"
    prefix:   /

amilio_core:
    resource: "@AmilioCoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"