amilio_core_homepage:
    path:     /
    defaults: { _controller: AmilioCoreBundle:Default:index }

amilio_core_channel_new:
    path:     /user/channel/new
    defaults: { _controller: AmilioCoreBundle:Channel:new }
    
amilio_core_channel_edit:
    path:     /user/channel/edit/{channel}/
    defaults: { _controller: AmilioCoreBundle:Channel:edit }
    
amilio_core_channel_store:
    path:     /user/channel/store/{channelId}
    defaults: { _controller: AmilioCoreBundle:Channel:store, channelId: -1}
    
amilio_core_channel_list:
    path:     /user/channel/list
    defaults: { _controller: AmilioCoreBundle:Channel:list }    
    
amilio_core_channel_show:
    path:     /c/{channel}/{canonicalName}/
    defaults: { _controller: AmilioCoreBundle:Channel:show }
    
amilio_core_channel_show_premium:
    path:     /p/{channelname}/
    defaults: { _controller: AmilioCoreBundle:Channel:showPremium } 
    
amilio_core_product_new:
    path:     /user/product/{channelId}/new
    defaults: { _controller: AmilioCoreBundle:Product:new }
    
amilio_core_product_store:
    path:     /user/product/{channelId}/store
    defaults: { _controller: AmilioCoreBundle:Product:store }
    
amilio_core_product_show:
    path:     /product/{product}/{canonicalName}.html
    defaults: { _controller: AmilioCoreBundle:Product:show }
    
amilio_core_product_remove:
    path:     /channel/remove/{channel}/{product}
    defaults: { _controller: AmilioCoreBundle:Product:remove }
    
amilio_core_product_share:
    path:     /user/share/product/{product}.html
    defaults: { _controller: AmilioCoreBundle:Product:share }
    
amilio_core_product_share_store:
    path:     /user/share/store/product/
    defaults: { _controller: AmilioCoreBundle:Product:shareStore }
    
amilio_core_channel_hottest:
    path:     /channels/hottest/
    defaults: { _controller: AmilioCoreBundle:Channel:showHottest }
    
# User Routes    

amilio_core_user_index:
    path:     /user/
    defaults: { _controller: AmilioCoreBundle:User:index }