amilio_core_homepage:
    path:     /
    defaults: { _controller: AmilioCoreBundle:Default:index }

amilio_core_channel_new:
    path:     /user/channel/new/{parentId}
    defaults: { _controller: AmilioCoreBundle:Channel:new, parentId = -1}
    
amilio_core_channel_edit:
    path:     /user/channel/edit/{channel}/
    defaults: { _controller: AmilioCoreBundle:Channel:edit }
    
amilio_core_channel_store:
    path:     /user/channel/store/{channelId}
    defaults: { _controller: AmilioCoreBundle:Channel:store, channelId: -1}
    
amilio_core_channel_delete:
    path:     /user/channel/delete/{channel}/
    defaults: { _controller: AmilioCoreBundle:Channel:delete}
    
amilio_core_channel_list:
    path:     /user/channel/list
    defaults: { _controller: AmilioCoreBundle:Channel:list }    
    
amilio_core_channel_show:
    path:     /c/{channel}/{canonicalName}.html
    defaults: { _controller: AmilioCoreBundle:Channel:show }
 
amilio_core_channel_add_favourite:
    path:     /user/channel/addFavourite/{channel}/
    defaults:  { _controller: AmilioCoreBundle:Channel:addFavourite }

amilio_core_channel_remove_favourite:
    path:     /user/channel/removeFavourite/{channel}/
    defaults:  { _controller: AmilioCoreBundle:Channel:removeFavourite }

amilio_core_channel_store_header_image:
    path:     /c/{channel}/
    defaults: { _controller: AmilioCoreBundle:Channel:storeHeaderImage }    
    
amilio_core_channel_show_premium:
    path:     /p/{channelname}/
    defaults: { _controller: AmilioCoreBundle:Channel:showPremium } 
    
amilio_core_product_new:
    path:     /user/product/{channelId}/new
    defaults: { _controller: AmilioCoreBundle:Product:new }
    
amilio_core_product_store:
    path:     /user/product/{channelId}/store
    defaults: { _controller: AmilioCoreBundle:Product:store }
    
amilio_core_product_show:
    path:     /product/{product}/{canonicalName}.html
    defaults: { _controller: AmilioCoreBundle:Product:show }
    
amilio_core_product_remove:
    path:     /user/product/remove/{element}/
    defaults: { _controller: AmilioCoreBundle:Product:remove }
    
amilio_core_product_share:
    path:     /user/share/product/{product}.html
    defaults: { _controller: AmilioCoreBundle:Product:share }
    
amilio_core_product_share_store:
    path:     /user/share/store/product/
    defaults: { _controller: AmilioCoreBundle:Product:shareStore }
    
amilio_core_channel_hottest:
    path:     /channels/
    defaults: { _controller: AmilioCoreBundle:Channel:showHottest }
    
# Static Pages
amilio_core_static_show:
    path:     /we/{blogurl}/
    defaults: { _controller: AmilioCoreBundle:Default:showStatic }
    
# User Routes    

amilio_core_user_index:
    path:     /user/{index}
    defaults: { _controller: AmilioCoreBundle:User:index, index: 1 }
