amilio_core_homepage:
    path:     /
    defaults: { _controller: AmilioCoreBundle:Default:index }

amilio_core_channel_new:
    path:     /channel/new
    defaults: { _controller: AmilioCoreBundle:Channel:new }
    
amilio_core_channel_store:
    path:     /channel/store
    defaults: { _controller: AmilioCoreBundle:Channel:store }
    