amilio_core_homepage:
    path:     /
    defaults: { _controller: AmilioCoreBundle:Default:index }

amilio_core_channel_new:
    path:     /user/channel/new
    defaults: { _controller: AmilioCoreBundle:Channel:new }
    
amilio_core_channel_store:
    path:     /user/channel/store
    defaults: { _controller: AmilioCoreBundle:Channel:store }
    
amilio_core_channel_list:
    path:     /user/channel/list
    defaults: { _controller: AmilioCoreBundle:Channel:list }    
    
amilio_core_channel_show:
    path:     /u/{userName}/{channelName}/
    defaults: { _controller: AmilioCoreBundle:Channel:show }
    
amilio_core_channel_show_premium:
    path:     /p/{channelname}/
    defaults: { _controller: AmilioCoreBundle:Channel:showPremium } 
    
amilio_core_product_new:
    path:     /user/product/{channelId}/new
    defaults: { _controller: AmilioCoreBundle:Product:new }
    
amilio_core_product_store:
    path:     /user/product/{channelId}/store
    defaults: { _controller: AmilioCoreBundle:Product:store }
    
amilio_core_product_show:
    path:     /product/{product}/{canonicalName}.html
    defaults: { _controller: AmilioCoreBundle:Product:show }