Amilio\CoreBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: Amilio\CoreBundle\Entity\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        url:
            type: string
            length: '1000'
        name:
            type: string
            length: '255'
        description:
            type: text
        price:
            type: float
        image:
            type: string
            length: '1000'
        manufacturer:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
