amilio_user_post_login:
    path:     /user/postLogin/
    defaults: { _controller: AmilioUserBundle:Default:postLogin }      
    
amilio_user_post_logout:
    path:     /user/postLogout/
    defaults: { _controller: AmilioUserBundle:Default:postLogout }