amilio_user_post_login:
    path:     /system/postLogin/
    defaults: { _controller: AmilioUserBundle:Default:postLogin }      
    
amilio_user_post_logout:
    path:     /system/postLogout/
    defaults: { _controller: AmilioUserBundle:Default:postLogout }

amilio_user_login:
    path:     /system/unsetcookies/
    defaults: { _controller: AmilioUserBundle:Default:showLogin }
    
amilio_user_notallowed:
    path:     /system/notallowed/
    defaults: { _controller: AmilioUserBundle:Default:notAllowed }
    
amilio_user_check_email:
    path:     /system/register/checkemail/
    defaults: { _controller: AmilioUserBundle:Default:checkEmail }